title: The CR7 Show
author:Sani Yusuf Abdulaziz
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is dedicated to proving how awesome cr7 is.

# social links
twitter_username: specialyas7 # DO NOT include the @ character, or else the build will fail!
github_username:  specialyas # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
